# Generated by Django 5.2.7 on 2025-12-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anemoneApp', '0003_artpiece_customitem_garment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizedPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_description', models.CharField(max_length=255)),
                ('result_image', models.ImageField(upload_to='ai_previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
