# Generated by Django 5.2.7 on 2025-12-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anemoneApp', '0004_customizedpreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomizedPreview',
        ),
        migrations.AddField(
            model_name='customitem',
            name='artist',
            field=models.CharField(default='ANCanvas', max_length=100),
        ),
        migrations.AddField(
            model_name='customitem',
            name='category',
            field=models.CharField(default='men', max_length=20),
        ),
        migrations.AddField(
            model_name='customitem',
            name='fabric',
            field=models.CharField(default='ANCanva', max_length=100),
        ),
        migrations.AddField(
            model_name='garment',
            name='category',
            field=models.CharField(default='men', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='men', max_length=20),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='artist',
            field=models.CharField(default='ANCanvas', max_length=100),
        ),
        migrations.AlterField(
            model_name='garment',
            name='fabric',
            field=models.CharField(default='ANCanva', max_length=100),
        ),
    ]
