# Generated by Django 5.2.7 on 2025-12-20 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anemoneApp', '0005_delete_customizedpreview_customitem_artist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_gallery/')),
                ('produt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='anemoneApp.product')),
            ],
        ),
    ]
